# Generated by Django 3.2.9 on 2021-11-12 08:39

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_footer_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='email',
            field=wagtail.core.fields.RichTextField(verbose_name='Email предприятия'),
        ),
        migrations.AlterField(
            model_name='header',
            name='email',
            field=wagtail.core.fields.RichTextField(verbose_name='Email предприятия'),
        ),
    ]
